on:
  push:
    branches: [ main ]

jobs:
  remote_ssh_job:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into remote server and execute command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            echo "Hello World"