on:
  push:
    branches: [ main ]

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print my secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: echo "MY_SECRET is $MY_SECRET"