on:
  push:
    branches: [ main ]

jobs:
  run_script_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: bash run.sh